module.exports = {
    INSERT_PRODUCT:`INSERT INTO PRODUCTS VALUES(?,?,?,?)`,
    FETCH_PRODUCT:`SELECT * FROM PRODUCTS`,
    UPDATE_PRODUCT:`UPDATE PRODUCTS SET PRICE=? WHERE PRODUCTID=?`,
    DELETE_PRODUCT:`DELETE FROM PRODUCTS WHERE PRODUCTID=?`,
    SEARCH_NAME:`SELECT * FROM PRODUCTS WHERE PRODUCTNAME=?`
}